services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: produtosdb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - eureka-net

  eureka-server:
    image: eurekaserver
    build:
      context: ../ex_eurekaServer
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - eureka-net

  produto-service:
    image: produto-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - mysql
    networks:
      - eureka-net

networks:
  eureka-net:

volumes:
  mysql-data:
